######### general networking configuration

# A unique ID for each Sota in a multi-Sota situation
robot_ID=1

# where to send-back received information
server_IP=10.10.10.10
net_http_port=8080

# should be fairly large to accommodate unexpected large packets
net_recv_buffer_size=2048

# may want to keep below 1500byte mtu
net_send_buffer_size=512

# packet sequence numbers always positive, when to wrap
net_seq_mod=1000000

# maximum number of packets to wait for missing before skipping ahead
net_UDP_waitbuffer_size=5
audio_receive_port=50002

# Sending audio stream from Sota's mic
audio_send_port=50001
microphone_sample_rate=16000

# bits
microphone_sample_size=16

# probably want to keep smaller than MTU since we're streaming it
microphone_buffer_size=512

# Receiving audio stream to play on Sota's speaker
speaker_sample_rate=16000

# bits
speaker_sample_size=16

# default to the same as the net buffer
speaker_buffer_size=512
