######### general networking configuration


####Some notes to help with setting buffers.
# - sota defaults to 16000hz, 16 bit.
#Mic:
#  - 256 byte read buffer is 128 frames, or 8ms. not small
#  - 128 byte read buffer is 64 frames or 4ms. takkes 6-7% CPU
#  - 64 byte read buffer is 32 frames, or 2ms. takes 8-9% CPU
#  - 4 byte read buffer is 2 frames, <1ms. Takes 35% CPU and drops packets



# A unique ID for each Sota in a multi-Sota situation. largely unused for now
robot_ID=1
net_http_port=8080

# maximum number of packets to wait for missing before skipping ahead
net_UDP_waitbuffer_size=5


##########MICROPHONE
# Sending audio stream from Sota's mic

# packet sequence numbers always positive, when to wrap
net_seq_mod=100

microphone_sample_rate=16000

# in bits
microphone_sample_size=16

microphone_channels=1

# probably want to keep smaller than MTU since we're streaming it
### MUST be an integer multiple of framesize, that is, k*(CHANNELS*BTYES/SAMPLE)
microphone_buffer_size=128


###########SPEAKER

# Receiving audio stream to play on Sota's speaker
speaker_sample_rate=16000

# bits
speaker_sample_size=16

speaker_channels=1

# default to the same as the net buffer
### this is a misnomer. this is the chunk size, not buffer. buffer should be in number of packets.
### a good place for considering updating the code
speaker_buffer_size=256